# TEST ENDPOINT SIGNUP
POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json

{
    "pseudo": "pouet",
    "insee": "02356",
    "password":"lolo@1234",
    "email": "cocololo@gmail.com"
}

###

# TEST ENDPOINT LOGIN 
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email": "ocololo@gmail.com",
    "password":"lolo@1234"
}

